#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

cd /app

#/usr/bin/dbus-daemon --system --nofork --print-address --nopidfile --nosyslog &

rfkill list bluetooth
bluetoothctl list
python3 tiltbridge_junior.py
